config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources "posts" do
    resources "comments", except: :show
  end
  resources "user_post_lists"
  resources :friend_requests
  resources :friends
  resources :groups do
    post "join_group", to: "groups#join_group"
    post "inviter_user/:user_id",as: "invite_user", to: "groups#invite_user"
    put "cancel", to: "groups#cancel"
    put "accept", to: "groups#accept"
    put "delete", to: "groups#delete"
    resources :user_groups do
      put "approve", to: "user_groups#approve"
      delete "decline", to: "user_groups#decline"
    end
    resources :group_posts do
      put "publish", to: "group_posts#publish"
      put "remove", to: "group_posts#remove"
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  include AASM
  after_create :approve_when_group_is_public
  belongs_to :user
  belongs_to :group
  belongs_to :inviter, class_name: 'User', optional: true
  has_many :group_posts
  enum role: { admin: 1, moderator: 2, normal: 3 }
  validates :user, presence: true, uniqueness: { scope: :group }

  aasm column: :state do
    state :pending, initial: true
    state :approved, :cancelled, :declined, :invited, :accepted, :deleted

    event :pend do
      transitions from: [:cancelled, :declined, :deleted], to: :pending
    end

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :decline do
      transitions from: :pending, to: :declined
    end

    event :cancel do
      transitions from: :pending, to: :cancelled
    end

    event :accept do
      transitions from: :invited, to: :accepted
    end

    event :delete do
      transitions from: :invited, to: :deleted
    end
  end

  def approve_when_group_is_public
    self.update(state: :approved) if group.public_group?
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_group_user, only: [:edit, :update, :destroy, :approve, :decline]
  before_action :set_group
  before_action :set_group_post, only: [:publish, :remove]

  def show
    authorize @group, :show?, policy_class: UserGroupPolicy
    @admins = @group.user_groups.admin
    @moderators = @group.user_groups.moderator
    @normal_users = @group.user_groups.normal.approved.or(@group.user_groups.normal.accepted)
    @pending_members = @group.user_groups.pending
    @invited_members = @group.user_groups.invited
    @pending_posts = @group.group_posts.pending
  end

  def edit
    authorize @group, :edit?, policy_class: UserGroupPolicy
  end

  def approve
    authorize @group, :approve?, policy_class: UserGroupPolicy
    if @user_group.may_approve? && @user_group.approve!
      flash[:notice] = "Successfully Accept"
      redirect_to group_user_group_path(@group, @user_group)
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to group_user_group_path(@group, @user_group)
    end
  end

  def decline
    authorize @group, :decline?, policy_class: UserGroupPolicy
    if @user_group.may_decline? && @user_group.decline!
      flash[:notice] = "Successfully Decline"
      redirect_to group_user_group_path(@group, @user_group)
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to group_user_group_path(@group, @user_group)
    end
  end

  def update
    authorize @group, :update?, policy_class: UserGroupPolicy
    @user_group.update(group_user_params)
    flash[:notice] = "User update successfully"
    redirect_to group_user_group_path
  end

  def destroy
    authorize @group, :destroy?, policy_class: UserGroupPolicy
    @user_group.destroy
    flash[:notice] = "User deleted successfully"
    redirect_to group_user_group_path
  end

  private

  def set_group_user
    @user_group = UserGroup.find(params[:id] || params[:user_group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_group_post
    @group_post = GroupPost.find(params[:id] || params[:group_post_id])
  end

  def group_user_params
    params.required(:user_group).permit(:role)
  end
end

app/views/user_groups/edit.html.erb
<%= form_with model: @user_group, url: group_user_group_path do |form| %>
  <h1><%= @user_group.user.email %></h1>
  <div class="card">
    <div class="card-body">
      <%= form.label :role, class: 'form-label' %>
      <%= form.select :role, options_for_select(UserGroup.roles.map { |key, value| [key.humanize, key] }), { prompt: "Select Role" }, class: 'form-control mt-1 mb-1' %>
      <%= form.submit "Update", class: 'btn btn-dark mt-2' %>
    </div>
  </div>
<% end %>

app/views/user_groups/index.html.erb
<% @members.each do |user_group| %>
  <%= user_group.id %>
<% end %>

app/views/user_groups/show.html.erb
<h1>Admins</h1>
<% @admins.each do |admin| %>
  <div class="card">
    <div class="card-body">
      <%= admin.user.email %><br>
      <div class="d-flex">
        <%= link_to "Edit", edit_group_user_group_path(@group, admin), class: 'btn btn-dark btn-sm' if UserGroupPolicy.new(current_user, @group).edit? && @group.owner.present? %>
        <%= button_to "Delete User", group_path(@group, admin), { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "btn btn-dark btn-sm mx-1" } if UserGroupPolicy.new(current_user, @group).destroy? %>
      </div>
    </div>
  </div>
<% end %>
<hr>
<h1>Moderator</h1>
<% @moderators.each do |moderator| %>
  <div class="card">
    <div class="card-body">
      <%= moderator.user.email %><br>
      <%= link_to "Edit", edit_group_user_group_path(@group, moderator), class: 'btn btn-dark btn-sm' if UserGroupPolicy.new(current_user, @group).edit? %>
      <%= button_to "Delete User", group_path(@group, moderator), { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "btn btn-dark btn-sm" } if UserGroupPolicy.new(current_user, @group).destroy? %>
    </div>
  </div>
<% end %>
<hr>
<h1>Normal User</h1>
<% @normal_users.each do |normal| %>
  <div class="card">
    <div class="card-body">
      <%= normal.user.email %><br>
      <%= link_to "Edit", edit_group_user_group_path(@group, normal), class: 'btn btn-dark btn-sm' if UserGroupPolicy.new(current_user, @group).edit? %>
      <%= button_to "Delete User", group_user_group_path(@group, normal), { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "btn-sm btn bi bi-trash3-fill dropdown-item" } if UserGroupPolicy.new(current_user, @group).destroy? %>
    </div>
  </div>
<% end %>
<hr>
<h1>Pending Members</h1>
<% @pending_members.each do |pending_member| %>
  <div class="card">
    <div class="card-body">
      <%= pending_member.user.email %><br>
      <div class="d-flex">
        <%= link_to "Edit", edit_group_user_group_path(@group, pending_member), class: 'btn btn-dark btn-sm' if UserGroupPolicy.new(current_user, @group).edit? %>
        <%= button_to "Approve", group_user_group_approve_path(@group, pending_member), { method: :put, class: 'btn btn-dark btn-sm mx-1', onclick: "return confirm('Are you sure you want to approve?')" } if UserGroupPolicy.new(current_user, @group).approve? %>
        <%= button_to "Decline", group_user_group_decline_path(@group, pending_member), { method: :delete, class: 'btn btn-dark btn-sm', onclick: "return confirm('Are you sure you want to decline?')" } if UserGroupPolicy.new(current_user, @group).decline? %>
      </div>
    </div>
  </div>
<% end %>
<hr>
<h1>Invited Members</h1>
<% @invited_members.each do |invited_member| %>
  <div class="card">
    <div class="card-body">
      <%= invited_member.user.email %><br>
      <div class="d-flex">
        <%= link_to "Edit", edit_group_user_group_path(@group, invited_member), class: 'btn btn-dark btn-sm' if UserGroupPolicy.new(current_user, @group).edit? %>
      </div>
    </div>
  </div>
<% end %>
<hr>
<h1>Pending Post</h1>
<% @pending_posts.each do |pending_post| %>
  <div class="card">
    <div class="card-body">
      <%= pending_post.content %><br>
      <%= button_to "Publish", group_group_post_publish_path(@group, pending_post), { method: :put, class: 'btn btn-dark btn-sm mx-1', onclick: "return confirm('Are you sure you want to publish?')" } %>
      <%= button_to "Remove", group_group_post_remove_path(@group, pending_post), { method: :put, class: 'btn btn-dark btn-sm', onclick: "return confirm('Are you sure you want to remove?')" } %>
      <div class="d-flex">
      </div>
    </div>
  </div>
<% end %>