config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources "posts" do
    resources "comments", except: :show
  end
  resources "user_post_lists"
  resources :friend_requests
  resources :friends
  resources :groups do
    post "join_group", to: "groups#join_group"
    post "inviter_user/:user_id",as: "invite_user", to: "groups#invite_user"
    put "cancel", to: "groups#cancel"
    put "accept", to: "groups#accept"
    put "delete", to: "groups#delete"
    resources :user_groups do
      put "approve", to: "user_groups#approve"
      delete "decline", to: "user_groups#decline"
    end
    resources :group_posts do
      put "publish", to: "group_posts#publish"
      put "remove", to: "group_posts#remove"
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  after_create :default_admin
  after_create :enable_invite
  validates_presence_of :description, :banner, :privacy
  validates :description, presence: true, length: { minimum: 15 }
  validates :name, presence: true, uniqueness: true
  belongs_to :owner, class_name: 'User'
  has_many :user_groups
  has_many :users, class_name: 'User', through: :user_groups
  has_many :group_posts
  enum privacy: { public_group: 0, hidden_group: 1 }
  mount_uploader :banner, ImageUploader

  def default_admin
    UserGroup.create!(role: :admin, group: self, user: owner, state: :approved)
  end

  def enable_invite
    self.update(can_invite?: true) if self.hidden_group?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, except: [:index, :new, :create]
  before_action :set_user, only: :invite_user

  def index
    @groups = Group.public_group if params[:group] == 'public'
    @join_groups = Group.includes(:user_groups).where(user_groups: { state: [:accepted, :approved], user: current_user }).or(Group.where(owner: current_user)) if params[:group] == 'join'
    @group_invitations = Group.includes(:user_groups).where(user_groups: { state: :invited, user: current_user }) if params[:group] == 'invitation'
  end

  def new
    @group = Group.new
  end

  def show
    @group_post = GroupPost.new
    authorize @group, :show?, policy_class: GroupPolicy
    @group_posts = @group.group_posts.published
    @friend_lists = current_user.friends.where.not(id: @group.user_groups.where(state: [:pending, :approved, :invited, :accepted]).pluck(:user_id))
  end

  def invite_user
    @user_group = @user.user_groups.find_by(group: @group)
    if @user_group
      @user_group.inviter = current_user
      @user_group.state = :invited
      flash[:notice] = "successfully invited!"
      redirect_to groups_path
    else
      @user_group = UserGroup.new
      @user_group.user = @user
      @user_group.group = @group
      @user_group.role = :normal
      @user_group.state = :invited
      @user_group.inviter = current_user
      if @user_group.save
        flash[:notice] = "successfully invited!"
        redirect_to groups_path
      else
        flash[:alert] = @user_group.errors.full_messages.join(", ")
        redirect_to groups_path
      end
    end
  end

  def join_group
    @user_group = current_user.user_groups.find_by(group: @group)
    if @user_group && @user_group.pend!
      flash[:notice] = "successfully join!"
      redirect_to groups_path
    else
      @user_group = UserGroup.new
      @user_group.user = current_user
      @user_group.role = :normal
      @user_group.group = @group
      if @user_group.save
        flash[:notice] = "successfully join!"
        redirect_to groups_path
      else
        flash[:alert] = @user_group.errors.full_messages.join(", ")
        redirect_to groups_path
      end
    end
  end

  def cancel
    authorize @group, :cancel?, policy_class: GroupPolicy
    if @group.user_groups.where(user: current_user).each do |user_group|
      user_group.may_cancel? && user_group.cancel!
    end
      flash[:notice] = "Successfully Cancel"
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to groups_path
    end
  end

  def accept
    authorize @group, :accept?, policy_class: GroupPolicy
    if @group.user_groups.where(user: current_user).each do |user_group|
      user_group.may_accept? && user_group.accept!
    end
      flash[:notice] = "Successfully Accept Invitation"
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to groups_path
    end
  end

  def delete
    authorize @group, :delete?, policy_class: GroupPolicy
    if @group.user_groups.where(user: current_user).each do |user_group|
      user_group.may_delete? && user_group.delete!
    end
      flash[:notice] = "Successfully Delete Invitation"
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to groups_path
    end
  end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    if @group.save
      flash[:notice] = "#{@group.name} was create successfully"
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to groups_path
    end
  end

  def edit
    authorize @group, :edit?, policy_class: GroupPolicy
  end

  def update
    authorize @group, :edit?, policy_class: GroupPolicy
    if @group.update(group_params)
      flash[:notice] = "#{@group.name} was update successfully"
      redirect_to group_path(@group)
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to groups_path(@group)
    end
  end

  def destroy
    authorize @group, :destroy?, policy_class: GroupPolicy
    if @group.destroy
      flash[:notice] = "#{@group.name} was deleted successfully"
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages.join(", ")
      redirect_to groups_path
    end
  end

  private

  def group_params
    params.required(:group).permit(:name, :privacy, :banner, :description, :role)
  end

  def set_group
    @group = Group.find(params[:id] || params[:group_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/views/groups/_form.html.erb
<%= form_with model: group, url: path do |form| %>
  <div class="">
    <div>
      <%= form.label "Group Name", class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div>
      <%= form.label "Description", class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>
    <div>
      <%= form.label "Banner", class: 'form-label' %>
      <%= form.file_field :banner, class: 'form-control' %>
    </div>
    <div>
      <%= form.label "Privacy", class: 'form-label' %>
      <%= form.select :privacy, options_for_select(Group.privacies.map { |key, value| [key.humanize, key] }), { prompt: "Select Privacy" }, class: 'form-control mt-1 mb-1' %>
    </div>
    <div>
      <%= form.submit class: 'form-control btn btn-dark mt-1' %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= render partial: 'form', locals: { group: @group, path: group_path } %>
<%= link_to "Back", groups_path, class: "btn btn-warning mt-2 form-control" %>

app/views/groups/index.html.erb
<%= link_to "", new_group_path, class: 'bi bi-plus btn btn-large border mb-3' %>
<%= link_to "All Groups", groups_path(group: :public), class: "btn btn-large border btn-outline-warning mb-3" if params[:group] == 'public' %>
<%= link_to "All Groups", groups_path(group: :public), class: "btn btn-large border btn-outline-dark mb-3" unless params[:group] == 'public' %>
<%= link_to "Joined Groups", groups_path(group: :join), class: "btn btn-large border btn-outline-warning mb-3" if params[:group] == 'join' %>
<%= link_to "Joined Groups", groups_path(group: :join), class: "btn btn-large border btn-outline-dark mb-3" unless params[:group] == 'join' %>
<%= link_to "Group Invitations", groups_path(group: :invited), class: "btn btn-large border btn-outline-warning mb-3" if params[:group] == 'invited' %>
<%= link_to "Group Invitations", groups_path(group: :invited), class: "btn btn-large border btn-outline-dark mb-3" unless params[:group] == 'invited' %>
<% @groups&.each do |group| %>
  <div class="card">
    <div class="card-body">
      <div><%= group.privacy.titleize %></div>
      <b><%= group.name %></b><br>
      <%= group.description %>
      <div><%= link_to "View Group Page", group_path(group), class: 'float-end btn btn-sm btn-dark' if group.user_groups.where(user: current_user).approved.exists? || group.user_groups.where(user: current_user).accepted.exists? %></div>
      <div><%= button_to "Cancel", group_cancel_path(group), class: 'float-end btn btn-sm btn-dark', method: :put if group.user_groups.where(user: current_user).pending.exists? && GroupPolicy.new(current_user, group).cancel? %></div>
      <div><%= button_to "Delete Invitation", group_delete_path(group), class: 'float-end btn btn-sm btn-dark mx-1', method: :put if group.user_groups.where(user: current_user).invited.exists? %></div>
      <div><%= button_to "Accept Invitation", group_accept_path(group), class: 'float-end btn btn-sm btn-dark', method: :put if group.user_groups.where(user: current_user).invited.exists? %></div>
      <div>
        <%= button_to "Join Group", { action: :join_group, controller: 'groups', group_id: group.id }, class: 'float-end btn btn-sm btn-dark', method: :post if group.user_groups.where(user: current_user).cancelled.exists? || group.user_groups.where(user: current_user).declined.exists? || !group.user_groups.where(user: current_user).exists? || group.user_groups.where(user: current_user).deleted.exists? %>
      </div>
    </div>
  </div>
<% end %>
<% @join_groups&.each do |group| %>
  <div class="card">
    <div class="card-body">
      <div><%= group.privacy.titleize %></div>
      <b><%= group.name %></b><br>
      <%= group.description %>
      <div><%= link_to "View Group Page", group_path(group), class: 'float-end btn btn-sm btn-dark' if group.user_groups.where(user: current_user).approved.exists? || group.user_groups.where(user: current_user).accepted.exists? %></div>
      <div><%= button_to "Cancel", group_cancel_path(group), class: 'float-end btn btn-sm btn-dark', method: :put if group.user_groups.where(user: current_user).pending.exists? && GroupPolicy.new(current_user, group).cancel? %></div>
      <div><%= button_to "Delete Invitation", group_delete_path(group), class: 'float-end btn btn-sm btn-dark mx-1', method: :put if group.user_groups.where(user: current_user).invited.exists? %></div>
      <div><%= button_to "Accept Invitation", group_accept_path(group), class: 'float-end btn btn-sm btn-dark', method: :put if group.user_groups.where(user: current_user).invited.exists? %></div>
      <div>
        <%= button_to "Join Group", { action: :join_group, controller: 'groups', group_id: group.id }, class: 'float-end btn btn-sm btn-dark', method: :post if group.user_groups.where(user: current_user).cancelled.exists? || group.user_groups.where(user: current_user).declined.exists? || !group.user_groups.where(user: current_user).exists? || group.user_groups.where(user: current_user).deleted.exists? %>
      </div>
    </div>
  </div>
<% end %>
<% @group_invitations&.each do |group| %>
  <div class="card">
    <div class="card-body">
      <div><%= group.privacy.titleize %></div>
      <b><%= group.name %></b><br>
      <%= group.description %>
      <div><%= link_to "View Group Page", group_path(group), class: 'float-end btn btn-sm btn-dark' if group.user_groups.where(user: current_user).approved.exists? || group.user_groups.where(user: current_user).accepted.exists? %></div>
      <div><%= button_to "Cancel", group_cancel_path(group), class: 'float-end btn btn-sm btn-dark', method: :put if group.user_groups.where(user: current_user).pending.exists? && GroupPolicy.new(current_user, group).cancel? %></div>
      <div><%= button_to "Delete Invitation", group_delete_path(group), class: 'float-end btn btn-sm btn-dark mx-1', method: :put if group.user_groups.where(user: current_user).invited.exists? %></div>
      <div><%= button_to "Accept Invitation", group_accept_path(group), class: 'float-end btn btn-sm btn-dark', method: :put if group.user_groups.where(user: current_user).invited.exists? %></div>
      <div>
        <%= button_to "Join Group", { action: :join_group, controller: 'groups', group_id: group.id }, class: 'float-end btn btn-sm btn-dark', method: :post if group.user_groups.where(user: current_user).cancelled.exists? || group.user_groups.where(user: current_user).declined.exists? || !group.user_groups.where(user: current_user).exists? || group.user_groups.where(user: current_user).deleted.exists? %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/new.html.erb
<%= render partial: 'form', locals: { group: @group, path: groups_path } %>
<%= link_to "Back", groups_path, class: "btn btn-warning mt-2 form-control" %>

app/views/groups/show.html.erb
<%= image_tag @group.banner.url, class: "w-100", height: "500" if @group.banner? %>
<%= @group.description %><br>
<%= @group.privacy %>
<div class="btn-group float-end">
  <%= link_to "Member List", group_user_group_path(@group), class: 'btn btn-dark btn-sm' %>
  <% if @group.can_invite? == true %>
  <div class="text-center">
    <button type="button" class="btn btn-dark btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <span>Invite</span>
    </button>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <section class="mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5 mb-5">
            <div class="container text-center">
              <div class="row d-flex justify-content-center align-items-center">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                  <div class="card-header">
                    <h5 class="text-center border bg-warning p-2">Invite list</h5>
                  </div>
                  <div class="card shadow-lg rounded-3">
                    <div class="card-body bg-light">
                      <% @friend_lists.each do |friend_list| %>
                        <p class="form-label"><%= friend_list.id %></p>
                        <div class="d-flex">
                          <p class="form-label"><%= friend_list.email %></p>
                          <%= button_to "Invite", group_invite_user_path(@group, friend_list), class: 'float-end btn btn-sm btn-dark', method: :post %>
                        </div>
                      <% end %>
                      <% if @friend_lists.blank? %>
                        <p>No friends to invite</p>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <button type="button" class="btn border border-1 btn-sm bi-three-dots" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
  </button>
  <ul class="dropdown-menu dropdown-menu-end dropdown-menu">
    <%= link_to "Edit Group", edit_group_path(@group), class: "btn-sm btn bi bi-pen dropdown-item" if GroupPolicy.new(current_user, @group).edit? %>
    <%= button_to "Delete Group", group_path(@group), { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "btn-sm btn bi bi-trash3-fill dropdown-item" } if GroupPolicy.new(current_user, @group).destroy? %>
  </ul>
</div>
<hr>
<% if user_signed_in? %>
  <div class="text-center" style="width: 100%;">
    <button type="button" class="btn btn-dark w-100" data-bs-toggle="modal" data-bs-target="#exampleModal<%= @group.id %>">
      <%= "Whats on your mind,#{pundit_user.email}" %>
    </button>
  </div>
  <div class="modal fade" id="exampleModal<%= @group.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <section class="mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5 mb-5">
            <div class="container text-center">
              <div class="row d-flex justify-content-center align-items-center">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                  <div class="card-header">
                    <h1 class="text-center border bg-warning p-2">Create Group Post</h1>
                  </div>
                  <div class="card shadow-lg rounded-3">
                    <div class="card-body bg-light">
                      <%= render partial: 'group_posts/form_group_new', locals: { group_post: @group_post, path: group_group_posts_path(@group) } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% @group_posts.each do |group_post| %>
  <div class="card shadow-lg rounded-3 mt-2">
    <div class="card-body bg-light">
      <div class="btn-group float-end">
        <button type="button" class="btn border border-1 btn-sm bi-three-dots" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
        </button>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu">
          <%= link_to "Show Post", group_group_post_path(@group, group_post), class: 'bi bi-eye btn-sm btn dropdown-item' %>
          <%= link_to "Edit Post", edit_group_group_post_path(@group, group_post), class: 'bi bi-pen btn-sm btn dropdown-item' %>
          <%= button_to "Delete Post", group_group_post_path(@group, group_post), { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "btn-sm btn bi bi-trash3-fill dropdown-item" } %>
        </ul>
      </div>
      <div>
        <%= group_post.user_group&.user&.email %><br>
        <span><%= time_ago_in_words(group_post.created_at) %> ago</span>
        <% if group_post.location? %>
<!--          <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%#= Geocoder.search(group_post.location).first&.city %> <%#= Geocoder.search(group_post.location).first&.region %>, <%#= Geocoder.search(group_post.location).first&.country %>">-->
          <span class="bi bi-geo-alt-fill"></span>
          </span>
        <% end %>
      </div>
      <hr>
      <h4 class="text-success"><%= group_post.content %></h4>
      <div class="text-center">
        <%= image_tag group_post.image.url, class: 'w-100', height: "400" if group_post.image? %>
      </div>
    </div>
  </div>
<% end %>