config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources "posts" do
    resources "comments", except: :show
  end
  resources "user_post_lists"
  resources :friend_requests
  resources :friends
  resources :groups do
    post "join_group", to: "groups#join_group"
    post "inviter_user/:user_id",as: "invite_user", to: "groups#invite_user"
    put "cancel", to: "groups#cancel"
    put "accept", to: "groups#accept"
    put "delete", to: "groups#delete"
    resources :user_groups do
      put "approve", to: "user_groups#approve"
      delete "decline", to: "user_groups#decline"
    end
    resources :group_posts do
      put "publish", to: "group_posts#publish"
      put "remove", to: "group_posts#remove"
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :text, :audience
  enum audience: { public_post: 0, private_post: 1, friends_only: 2 }
  has_many :comments
  belongs_to :user
  mount_uploader :image, ImageUploader
  default_scope { order("created_at DESC") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  Pundit::Authorization
  after_action :verify_authorized, except: [:index, :create, :show]
  before_action :set_post, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, except: :index

  def index
    @posts = current_user.posts.or(Post.public_post).or(Post.where(user: current_user.friends).friends_only) if current_user
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if Rails.env.development?
      @post.location = Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    else
      @post.location = request.remote_ip
    end
    if @post.save
      flash[:notice] = "Post created successfully"
      redirect_to posts_path
    else
      flash[:alert] = @post.errors.full_messages.join(", ")
      redirect_to posts_path
    end
  end

  def edit
    authorize @post, :edit?, policy_class: PostPolicy
  end

  def show
    authorize @post, :show?, policy_class: PostPolicy
  end

  def update
    authorize @post, :update?, policy_class: PostPolicy
    @post.update(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post update successfully"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    authorize @post, :destroy?, policy_class: PostPolicy
    if @post.destroy
      flash[:notice] = "Post delete successfully"
      redirect_to posts_path
    else
      flash[:alert] = @post.errors.full_messages.join(", ")
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.required(:post).permit(:text, :image, :location, :audience)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: path do |f| %>
  <div class="text-center" style="width: 40%;">
    <%= f.label :audience, class: 'bi bi-people' %>
    <%= f.select :audience, options_for_select(Post.audiences.map { |key, value| [key.humanize, key] }), {}, class: 'text-center form-control form-control-sm mt-1 mb-1' %>
  </div>
  <div>
    <%= f.text_area :text, class: 'form-control mt-1 mb-1', style: 'font-size: 25px;', placeholder: "Whats on your mind, #{current_user.email}" %>
  </div>
  <div class="row">
    <div class="col-7">
      <h3>Add to your post!</h3>
    </div>
    <div class="image-upload col-3">
      <label for="file-input">
        <h3 class="bi bi-image"></h3>
      </label>
      <%= f.file_field :image, id: 'file-input' %>
    </div>
  </div>
  <hr>
  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<section class="mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5 mb-5">
  <div class="container text-center" style="width: 40%;">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
        <div class="card-header">
          <h1 class="text-center border bg-warning p-2">Edit Post</h1>
        </div>
        <div class="card shadow-lg rounded-3">
          <div class="card-body bg-light">
            <%= render partial: 'form', locals: { post: @post, path: post_path } %>
            <%= link_to "Back", posts_path, class: "btn btn-warning mt-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5 mb-3">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-sm-12 col-md-11 col-lg-10 col-xl-9 col-xxl-8">
        <div class="card-header">
          <h1 class="text-center border bg-warning p-2">KODA SOCIAL MEDIA</h1>
        </div>
        <% if user_signed_in? %>
          <div class="text-center" style="width: 100%;">
            <button type="button" class="btn btn-dark w-100" data-bs-toggle="modal" data-bs-target="#exampleModal">
              <%= "Whats on your mind,#{pundit_user.email}" %>
            </button>
          </div>
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-body">
                  <section class="mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5 mb-5">
                    <div class="container text-center">
                      <div class="row d-flex justify-content-center align-items-center">
                        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                          <div class="card-header">
                            <h1 class="text-center border bg-warning p-2">Create Post</h1>
                          </div>
                          <div class="card shadow-lg rounded-3">
                            <div class="card-body bg-light">
                              <%= render partial: 'form', locals: { post: @post, path: posts_path } %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% @posts&.each do |post| %>
          <div class="card shadow-lg rounded-3 mt-2">
            <div class="card-body bg-light">
              <div class="btn-group float-end">
                <button type="button" class="btn border border-1 btn-sm bi-three-dots" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                </button>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu">
                  <%= link_to "Show Post", post_path(post), class: 'bi bi-eye btn-sm btn dropdown-item' %>
                  <%= link_to "Edit Post", edit_post_path(post), class: 'bi bi-pen btn-sm btn dropdown-item' if policy(post).edit? %>
                  <%= button_to "Delete Post", post_path(post), { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "btn-sm btn bi bi-trash3-fill dropdown-item" } if policy(post).destroy? %>
                </ul>
              </div>
              <div>
                <%= post.user.email %><br>
                <span><%= time_ago_in_words(post.created_at) %></span>
                <% if post.public_post? %>
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= post.audience %>">
                  <span class="bi bi-globe-americas"></span>
                </span>
                <% end %>
                <% if post.private_post? %>
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= post.audience %>">
                  <span class="bi bi-lock-fill"></span>
                </span>
                <% end %>
                <% if post.friends_only? %>
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= post.audience %>">
                  <span class="bi bi-people-fill"></span>
                </span>
                <% end %>
                <% if post.location? %>
                  <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= Geocoder.search(post.location).first&.city %> <%= Geocoder.search(post.location).first&.region %>, <%= Geocoder.search(post.location).first&.country %>">
                  <span class="bi bi-geo-alt-fill"></span>
                  </span>
                <% end %>
              </div>
              <hr>
              <h4 class="text-success"><%= post.text %></h4>
              <div class="text-center">
                <%= image_tag post.image.url, class: 'w-100', height: "400" if post.image? %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 mt-xxl-5 mb-5">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
        <div class="card-header border bg-warning p-2">
          <%= link_to "", posts_path, class: 'float-end btn btn-sm border border-1 bi bi-x-circle' %>
          <h5><%= @post.user.email %></h5>
          <h5 class="bi bi-person"><%= @post.audience %></h5>
        </div>
        <div class="card shadow-lg rounded-3">
          <div class="card-body bg-light">
            <div class="">
              <h4 class="mb-3"><%= @post.text %></h4>
              <% if @post.image? %>
                <%= image_tag @post.image.url, class: 'w-100', height: "400" %><br>
              <% end %>
            </div>
            <div class="accordion mt-4" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <h5>Comments</h5>
                  </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <div>
                      <%= render partial: 'comments/new_form', locals: { post: @post.comments.new, path: post_comments_path(@post) } %>
                    </div>
                    <div>
                      <% @post.comments.each do |comment| %>
                        <div class="btn-group float-end">
                          <button type="button" class="btn border border-1 btn-sm bi-three-dots" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                          </button>
                          <ul class="dropdown-menu dropdown-menu-end dropdown-menu">
                            <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment), class: 'bi bi-pen btn-sm btn dropdown-item' if policy(comment).edit? %>
                            <%= button_to 'Delete Comment', post_comment_path(@post, comment), class: 'bi bi-x-circle-fill btn-sm btn dropdown-item', :onclick => "return confirm('Are you sure you want to delete?')", method: :delete if policy(comment).destroy? %>
                          </ul>
                        </div>
                        <%= comment.user&.email %><br>
                        <%= comment.content %><br>
                        <% if comment.created_at.present? %>
                          <span><%= time_ago_in_words(comment.created_at) %> ago</span>
                        <% end %>
                        <hr>
                      <% end %>
                      <% if @post.comments.blank? %>
                        <span>No comment show, you can add comment!</span>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>