config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources "posts" do
    resources "comments", except: :show
  end
  resources "user_post_lists"
  resources :friend_requests
  resources :friends
  resources :groups do
    post "join_group", to: "groups#join_group"
    post "inviter_user/:user_id",as: "invite_user", to: "groups#invite_user"
    put "cancel", to: "groups#cancel"
    put "accept", to: "groups#accept"
    put "delete", to: "groups#delete"
    resources :user_groups do
      put "approve", to: "user_groups#approve"
      delete "decline", to: "user_groups#decline"
    end
    resources :group_posts do
      put "publish", to: "group_posts#publish"
      put "remove", to: "group_posts#remove"
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-center text-white sticky-top border-bottom">
  <div class="container">
    <span class="navbar-brand"><%= link_to 'KSM', posts_path, class: "btn btn-outline-light btn-floating m-1" %></span>
    <div class="d-flex">
      <div class="btn-group" role="group">
        <% if user_signed_in? %>
          <%= link_to "Groups", groups_path(group: :public), class: "btn btn-outline-light btn-floating m-1" %>
          <%= link_to "Friends", friends_path, class: "btn btn-outline-light btn-floating m-1" %>
          <%= link_to "Find Friends", friend_requests_path, class: "btn btn-outline-light btn-floating m-1" %>
          <%= link_to pundit_user.email, user_post_lists_path(post: 'public'), class: "btn btn-outline-light btn-floating m-1" %>
        <% end %>
        <div class="btn-group">
          <button type="button" class="btn btn-outline-light btn-floating m-1 bi-list-task" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu dropdown-menu-end bg-light">
            <% if user_signed_in? %>
              <%= button_to "Log Out", destroy_user_session_path, { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "dropdown-item" } %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="font-family: system-ui;">
    <%= render 'layouts/header' %>
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>